services:
  couchdb:
    image: couchdb:3
    container_name: couchdb-local
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: adminpass
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
